version: "3.9"

services:
  dialoqbase:
    image: node:18-slim
    container_name: alphabot
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@alphabot-pg:5432/alphabot?connection_limit=15&pool_timeout=0
      DB_REDIS_URL: redis://redis:6379
    env_file:
      - .env
    depends_on:
      - alphabot-pg
      - redis
    volumes:
      - .uploads:/app/uploads

  alphabot-pg:
    image: ankane/pgvector:latest
    container_name: alphabot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alphabot
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data
